services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: batchhawk
      POSTGRES_USER: batchhawk
      POSTGRES_PASSWORD: batchhawk
    ports:
      - '5432:5432'

  keycloak:
    image: 'quay.io/keycloak/keycloak:26.2'
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
      - ./docker/keycloak/themes:/opt/keycloak/themes
    ports:
      - '8180:8080'

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'