spring:
  application:
    name: batch-hawk
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    out-of-order: true
  web:
    error:
      include-stacktrace: never

batchhawk:
  refresh-interval-hours: 72
  max-run-minutes: 10

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      file: ../compose.yaml
      lifecycle-management: start-only
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration/dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/batchhawk

management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info,env,beans

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info
