-- Roasters sourced from community espresso tracking dataset.
-- Skips roasters already present in V99999.

INSERT INTO roasters (name, website_url, city, state, is_active, moderation_status, integration_type, created_at, updated_at)
VALUES
    ('Stumptown Coffee Roasters',           'https://www.stumptowncoffee.com',          'Portland',             'OR', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Barrington Coffee',                   'https://barringtoncoffee.com',             'Lee',                  'MA', TRUE, 'APPROVED', 'UNKNOWN',      now(), now()),
    ('Commonplace Coffee',                  'https://commonplacecoffee.com',            'Pittsburgh',           'PA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Olympia Coffee',                      'https://www.olympiacoffee.com',            'Olympia',              'WA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Metric Coffee',                       'https://metriccoffee.com',                 'Chicago',              'IL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Blue Bottle Coffee',                  'https://bluebottlecoffee.com',             'Oakland',              'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('George Howell Coffee',                'https://georgehowellcoffee.com',           'Boston',               'MA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Press Coffee',                        'https://presscoffee.com',                  'Phoenix',              'AZ', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Sparrows Coffee',                     'https://brewsparrows.com',                 'Grand Rapids',         'MI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Prodigal Coffee',                     'https://getprodigal.com',                  'Boulder',              'CO', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Coffee by Design',                    'https://coffeebydesign.com',               'Portland',             'ME', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Rwanda Bean',                         'https://rwandabean.com',                   'Portland',             'ME', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Black Elm Coffee',                    'https://blackelm.coffee',                  'Gallatin',             'TN', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Joe Coffee',                          'https://joecoffeecompany.com',             'New York',             'NY', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Sweet Beans Coffee Company',          'https://sweetbeanscc.com',                 'Omaha',                'NE', TRUE, 'APPROVED', 'UNKNOWN',      now(), now()),
    ('Bones Coffee Co.',                    'https://bonescoffee.com',                  'Cape Coral',           'FL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Native Coffee Co.',                   'https://thenativecoffeecompany.com',       'Dallas',               'TX', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Selfsame Coffee',                     'https://selfsamecoffee.com',               'Fort Wayne',           'IN', TRUE, 'APPROVED', 'UNKNOWN',      now(), now()),
    ('Mothership Coffee Roasters',          'https://mothershipcoffee.com',             'Las Vegas',            'NV', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Small Planes Coffee',                 'https://smallplanescoffee.com',            'Washington',           'DC', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Sodality Coffee',                     'https://sodality.coffee',                  'Elkhorn',              'NE', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Rising Star Coffee',                  'https://risingstarcoffee.com',             'Cleveland',            'OH', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Cartel Roasting Co.',                 'https://cartelroasting.co',                'Phoenix',              'AZ', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Hyperion Coffee',                     'https://hyperioncoffee.com',               'Ypsilanti',            'MI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('517 Coffee Company',                  'https://www.517coffeecompany.com',         'Lansing',              'MI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Chromatic Coffee',                    'https://www.chromaticcoffee.com',          'San Jose',             'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Denim Coffee',                        'https://www.denimcoffeecompany.com',       'Chambersburg',         'PA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Kitty Town Coffee',                   'https://www.kittytowncoffee.com',          'Lansdale',             'PA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Experimental Coffee',                 'https://experimental.coffee',              'Chicago',              'IL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Laheey Coffee Roasters',              'https://laheeycoffee.com',                 'Columbia',             'MD', TRUE, 'APPROVED', 'UNKNOWN',      now(), now()),
    ('Silk City Coffee',                    'https://silkcitycoffee.com',               'Manchester',           'CT', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Backroads Coffee',                    'https://www.backroadscoffee.com',          'Hayward',              'WI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('LiftUp Roast',                        'https://liftuproast.com',                  'Berkeley',             'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Caje Coffee Roasters',                'https://caje.coffee',                      'Santa Barbara',        'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Offset Coffee Roasters',              'https://www.offsetcoffee.com',             'El Segundo',           'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Valentine Coffee Roasting Company',   'https://www.valentinecoffeeco.com',        'Milwaukee',            'WI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Puroast',                             'https://puroast.com',                      'High Point',           'NC', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Fidalgo Coffee Roasters',             'https://fidalgocoffee.com',                'Burlington',           'WA', TRUE, 'APPROVED', 'WOO_COMMERCE', now(), now()),
    ('Wells Coffee Company',                'https://wellscoffees.com',                 'Fort Lauderdale',      'FL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Bicycle Coffee',                      'https://bicyclecoffee.com',                'Oakland',              'CA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Ember and Bean Roasting Co.',         'https://emberandbeanroasting.com',         'Hudson',               'WI', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Gracenote Coffee',                    'https://gracenotecoffee.com',              'Boston',               'MA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Deeper Roots Coffee',                 'https://deeperrootscoffee.com',            'Cincinnati',           'OH', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Function Coffee Co.',                 'https://www.functioncoffeeco.com',         'Northlake',            'TX', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('XOZIO Coffee & Provisions',           'https://xoziocoffeeandprovisions.com',     'Chattanooga',          'TN', TRUE, 'APPROVED', 'UNKNOWN',      now(), now()),
    ('Opossum Coffee Company',              'https://www.opossumcoffeecompany.com',     'Lucedale',             'MS', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Newport Coffee',                      'https://www.newport-coffee.com',           'Deerfield',            'IL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Ace Coffee Outpost',                  'https://acecoffeeoutpost.com',             'Long Island',          'NY', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('CBC Roasters',                        'https://www.cbcroasters.com',              'Arlington Heights',    'IL', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Simple Roast',                        'https://simpleroastcoffee.com',            'Auburn',               'NY', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Mystic Monk Coffee',                  'https://mysticmonkcoffee.com',             'Clark',                'WY', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Gigawatt Coffee Roasters',            'https://www.gigawattcoffeeroasters.com',   NULL,                   NULL, TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Kuma Coffee',                         'https://kumacoffee.com',                   'Seattle',              'WA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Dean''s Beans',                       'https://deansbeans.com',                   'Orange',               'MA', TRUE, 'APPROVED', 'WOO_COMMERCE', now(), now()),
    ('Dillanos Coffee Roasters',            'https://dillanos.com',                     'Sumner',               'WA', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Atlas Coffee Club',                   'https://atlascoffeeclub.com',              'Austin',               'TX', TRUE, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Zanzibar''s Coffee',                  'https://zanzibarscoffee.com',              'Des Moines',           'IA', TRUE, 'APPROVED', 'UNKNOWN',      now(), now());