INSERT INTO roasters (name, website_url, is_active, moderation_status, integration_type, created_at, updated_at)
VALUES
    ('Onyx Coffee Lab',         'https://onyxcoffeelab.com',         true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Verve Coffee Roasters',   'https://vervecoffee.com',           true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Passenger Coffee',        'https://passengercoffee.com',       true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Equator Coffees',         'https://equatorcoffees.com',        true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Coava Coffee Roasters',   'https://coavacoffee.com',           true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Ruby Coffee Roasters',    'https://rubycoffeeroasters.com',    true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Dogwood Coffee Co.',      'https://dogwoodcoffee.com',         true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('PT''s Coffee Roasting',   'https://ptscoffee.com',             true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Madcap Coffee Company',   'https://madcapcoffee.com',          true, 'APPROVED', 'SHOPIFY', now(), now()),
    ('Methodical Coffee',             'https://methodicalcoffee.com',          true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Arcadia Coffee Roasters',       'https://www.arcadia.coffee',            true, 'APPROVED', 'CUSTOM',       now(), now()),
    ('Spokesman Coffee',              'https://www.spokesmancoffee.com',       true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Malone Coffee',                 'https://store.malonecoffee.com',        true, 'APPROVED', 'CUSTOM',       now(), now()),
    ('Red Horn Coffee',               'https://redhornbrew.com',               true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Anderson Coffee',               'https://andersonscoffee.com',           true, 'APPROVED', 'WOO_COMMERCE', now(), now()),
    ('Barrett''s Coffee',             'https://www.barrettscoffee.com',        true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Eiland Coffee Roasters',        'https://www.eilandcoffee.com',          true, 'APPROVED', 'CUSTOM',       now(), now()),
    ('Anchorhead Coffee',             'https://anchorheadcoffee.com',          true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Commander Coffee',              'https://thecommandercoffee.com',        true, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('What''s Brewing Coffee Roasters', 'https://www.sacoffeeroasters.com',    true, 'APPROVED', 'CUSTOM',       now(), now()),
    ('Counter Culture Coffee',          'https://counterculturecoffee.com',    false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Intelligentsia Coffee',           'https://intelligentsia.com',          false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Heart Coffee Roasters',           'https://heartroasters.com',           false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Sey Coffee',                      'https://seycoffee.com',               false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Black & White Coffee Roasters',   'https://blackwhiteroasters.com',      false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Proud Mary Coffee',               'https://proudmarycoffee.com',         false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Tandem Coffee Roasters',          'https://tandemcoffee.com',            false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Sweet Bloom Coffee Roasters',     'https://sweetbloomcoffee.com',        false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Bird Rock Coffee Roasters',       'https://birdrockcoffee.com',          false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('ReAnimator Coffee',               'https://reanimatorcoffee.com',        false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Cat & Cloud Coffee',              'https://catandcloud.com',             false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Novo Coffee',                     'https://novocoffee.com',              false, 'APPROVED', 'WOO_COMMERCE', now(), now()),
    ('Cuvée Coffee',                    'https://cuveecoffee.com',             false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Perc Coffee',                     'https://perccoffee.com',              false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Devoción',                        'https://devocion.com',                false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Monogram Coffee',                 'https://monogramcoffee.com',          false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Greater Goods Coffee Roasting',   'https://greatergoodsroasting.com',    false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Klatch Coffee',                   'https://klatchcoffee.com',            false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('JBC Coffee Roasters',             'https://jbccoffeeroasters.com',       false, 'APPROVED', 'WOO_COMMERCE', now(), now()),
    ('Irving Farm Coffee Roasters',     'https://irvingfarmcoffee.com',        false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Heirloom Coffee Roasters',        'https://heirloomcoffeeroasters.com',  false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Wonderstate Coffee',              'https://wonderstate.com',             false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Mudhouse Coffee Roasters',        'https://mudhouse.com',                false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Subtext Coffee Roasters',         'https://subtext.coffee',              false, 'APPROVED', 'SHOPIFY',      now(), now()),
    ('Red Rooster Coffee Roasters',     'https://redroostercoffee.com',        false, 'APPROVED', 'CUSTOM',       now(), now());

