/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/worker/runs/{runId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimNextJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roasters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompleteRunRequest: {
            status?: string;
            products?: components["schemas"]["ProductUpdateRequest"][];
            notes?: string;
            roasterUpdate?: components["schemas"]["RoasterUpdateRequest"];
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            siteHints?: string;
        };
        ProductUpdateRequest: {
            name?: string;
            roastLevel?: string;
            productType?: string;
            originCountry?: string;
            originRegion?: string;
            process?: string;
            brewMethods?: string[];
            flavorProfile?: string[];
            availabilityType?: string;
            description?: string;
            productUrl?: string;
            externalProductId?: string;
            offersGrinding?: boolean;
            variants?: components["schemas"]["VariantInfo"][];
            /** Format: int32 */
            priceInCents?: number;
            /** Format: int32 */
            bagSize?: number;
            bagUnit?: string;
            inStock?: boolean;
            decaf?: boolean;
        };
        RoasterUpdateRequest: {
            city?: string;
            state?: string;
            logoUrl?: string;
        };
        VariantInfo: {
            /** Format: int32 */
            bagSize?: number;
            bagUnit?: string;
            /** Format: int32 */
            priceInCents?: number;
            inStock?: boolean;
        };
        NextJobResponse: {
            /** Format: int64 */
            runId?: number;
            /** Format: int64 */
            roasterId?: number;
            websiteUrl?: string;
            emailListUrl?: string;
            urlHints?: string;
            integrationType?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageRoasterResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["RoasterResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        RoasterResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            websiteUrl?: string;
            emailListUrl?: string;
            city?: string;
            state?: string;
            logoUrl?: string;
            active: boolean;
            /** @enum {string} */
            moderationStatus: "PENDING" | "APPROVED" | "REJECTED";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        PageProductResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProductResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        ProductObservationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            bagSize?: number;
            bagSizeUnit?: string;
            bagSizeOz?: number;
            priceUsd?: number;
            pricePerOz?: number;
            inStock?: boolean;
            /** Format: date-time */
            observedAt: string;
        };
        ProductResponse: {
            /** Format: uuid */
            id: string;
            roaster: components["schemas"]["RoasterResponse"];
            name: string;
            roastLevel?: string;
            productType?: string;
            originCountry?: string;
            originRegion?: string;
            process?: string;
            brewMethods?: string[];
            flavorProfile?: string[];
            decaf: boolean;
            offersGrinding: boolean;
            availabilityType?: string;
            description?: string;
            productUrl?: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            variants: components["schemas"]["ProductObservationResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    completeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRunRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claimNextJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NextJobResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query: {
                name?: string;
                activeOnly?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRoasterResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoasterResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                roasterId?: string;
                name?: string;
                activeOnly?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageProductResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
        };
    };
}
